name = "Uxn"
uuid = "d47ca433-c061-4175-9b2e-5c2760ce8240"
authors = ["Ismael Venegas Castelló"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
